services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - wallet_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../wallet_billing/.env


volumes:
  wallet_postgres_data:
