services:
  backend:
    container_name: web
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh /entrypoint.sh"
    depends_on:
      - postgres
    volumes:
      - ../backend:/app/
    env_file:
      - ../backend/.env

